name: mock-registry
version: 0.1.0.0
github: "nammayatri/beckn-gateway"
license: AllRightsReserved
author: "nammayatri"
maintainer: "nammayatri"
copyright: "nammayatri.in"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/nammayatri/beckn-gateway/blob/main/app/mock-registry/README.md>

default-extensions:
  - NoImplicitPrelude
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - GADTs
  - UndecidableInstances
  - DeriveAnyClass
  - DeriveGeneric
  - TypeOperators
  - DuplicateRecordFields
  - RecordWildCards
  - OverloadedStrings
  - TypeApplications

dependencies:
  - base >= 4.7 && < 5
  - euler-hs
  - record-hasfield
  - record-dot-preprocessor
  - servant-server
  - warp
  - time
  - text
  - persistent
  - servant-client
  - openapi3
  - aeson
  - regex-compat
  - unordered-containers

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -fplugin=RecordDotPreprocessor
  - -Wwarn=ambiguous-fields

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -fhide-source-paths
    - -Wno-unrecognised-pragmas
    - -Werror
    - -Wwarn=ambiguous-fields
  dependencies:
    - mobility-core

executables:
  mock-registry-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mock-registry
