name: beckn-gateway
version: 0.1.0.0
github: "nammayatri/beckn-gateway"
license: AllRightsReserved
author: "nammayatri"
maintainer: "nammayatri"
copyright: "nammayatri.in"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/nammayatri/beckn-gateway/blob/main/app/gateway/README.md>

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - BlockArguments
  - TypeSynonymInstances
  - UndecidableInstances

dependencies:
  - base >= 4.7 && < 5
  - euler-hs
  - record-hasfield
  - record-dot-preprocessor
  - unordered-containers

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wunused-imports
  - -Werror
  - -fplugin=RecordDotPreprocessor
  - -Wwarn=ambiguous-fields

library:
  source-dirs: src
  ghc-options:
    - -Wincomplete-uni-patterns
  dependencies:
    - aeson
    - mobility-core
    - bytestring
    - cache
    - containers
    - servant-client
    - servant-server
    - text
    - unordered-containers
    - wai
    - warp
    - http-client
    - hashmap

executables:
  beckn-gateway-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
      - -Wincomplete-uni-patterns
    dependencies:
      - beckn-gateway
